/**
 * A large, diverse, kid-safe English word bank for the typing/arcade/shark
 * modes. Generated by a 14-agent fan-out across themes (animals, food, nature,
 * actions, school, body/family, colors/shapes, feelings, places, travel,
 * sports, space, sea, jobs), then de-duplicated and re-bucketed by length:
 * EASY 2-4 letters, MEDIUM 5-6, HARD 7-12. ASCII only, no proper nouns.
 *
 * Words double as English listening practice — the game reads each one aloud.
 */
export const EASY: string[] = [
  'ant', 'arm', 'art', 'aunt', 'baby', 'bag', 'bake', 'ball', 'barn', 'bat',
  'bean', 'bed', 'bee', 'bell', 'big', 'bike', 'bird', 'blue', 'boat', 'book',
  'bot', 'boy', 'bud', 'bun', 'bus', 'busy', 'cab', 'cake', 'calm', 'cap',
  'car', 'cat', 'chin', 'clap', 'cook', 'cool', 'corn', 'cow', 'cozy', 'crab',
  'cube', 'cute', 'dad', 'deer', 'desk', 'dew', 'dig', 'dive', 'dock', 'dog',
  'door', 'dot', 'draw', 'duck', 'ear', 'eat', 'egg', 'eye', 'fair', 'fern',
  'fig', 'fin', 'fish', 'five', 'fix', 'fly', 'foam', 'fog', 'foot', 'four',
  'fox', 'frog', 'fun', 'game', 'gate', 'gem', 'girl', 'glad', 'glue', 'goal',
  'goat', 'gold', 'gray', 'gum', 'ham', 'hand', 'hat', 'hay', 'hen', 'hill',
  'hip', 'home', 'hop', 'hug', 'ice', 'ink', 'jam', 'jar', 'jaw', 'jet',
  'joy', 'jump', 'key', 'kick', 'kid', 'kind', 'kite', 'kiwi', 'lab', 'lamp',
  'leaf', 'leap', 'leg', 'lime', 'lip', 'mad', 'map', 'math', 'milk', 'mix',
  'mole', 'mom', 'moon', 'mop', 'moss', 'mud', 'nap', 'neat', 'net', 'nine',
  'nose', 'note', 'nut', 'oar', 'oat', 'one', 'oval', 'owl', 'page', 'pan',
  'park', 'pea', 'pear', 'pen', 'pie', 'pig', 'pink', 'play', 'plum', 'pond',
  'pool', 'pot', 'pup', 'quiz', 'race', 'raft', 'rain', 'ram', 'ray', 'read',
  'red', 'reef', 'rib', 'rice', 'ride', 'road', 'roll', 'roof', 'room', 'rose',
  'rug', 'run', 'sad', 'sail', 'salt', 'sand', 'saw', 'sea', 'seal', 'seed',
  'shed', 'ship', 'shy', 'sing', 'sink', 'sip', 'sit', 'six', 'skip', 'sky',
  'snow', 'sofa', 'soft', 'son', 'soup', 'spin', 'star', 'step', 'sun', 'surf',
  'swim', 'taco', 'tag', 'tan', 'tap', 'tape', 'taxi', 'team', 'ten', 'tent',
  'test', 'tide', 'tidy', 'tiny', 'tire', 'toe', 'town', 'toy', 'tree', 'trip',
  'twin', 'two', 'van', 'vine', 'walk', 'wall', 'warm', 'wave', 'wet', 'win',
  'wind', 'wing', 'yard', 'zap', 'zero',
]

export const MEDIUM: string[] = [
  'adult', 'alien', 'alpha', 'anchor', 'ankle', 'apple', 'apron', 'attic', 'autumn', 'bacon',
  'baker', 'banana', 'beach', 'bench', 'berry', 'black', 'blast', 'blocks', 'boats', 'bounce',
  'branch', 'brave', 'bread', 'breeze', 'bridge', 'bright', 'broom', 'brown', 'brush', 'build',
  'bunny', 'cabin', 'camel', 'candy', 'canoe', 'carrot', 'carry', 'castle', 'catch', 'chair',
  'chart', 'cheek', 'cheery', 'cherry', 'child', 'circle', 'class', 'clean', 'clerk', 'climb',
  'cloud', 'color', 'comet', 'cookie', 'coral', 'couch', 'count', 'court', 'cousin', 'crayon',
  'cream', 'dance', 'diver', 'dragon', 'dream', 'drift', 'driver', 'eagle', 'eight', 'elbow',
  'eleven', 'engine', 'eraser', 'fancy', 'father', 'fence', 'ferry', 'field', 'float', 'floor',
  'flower', 'fluffy', 'folder', 'follow', 'forest', 'friend', 'frost', 'fruit', 'funny', 'galaxy',
  'garden', 'gather', 'gears', 'gecko', 'gentle', 'giggle', 'globe', 'goose', 'grape', 'grass',
  'green', 'happy', 'harbor', 'heart', 'hockey', 'honest', 'honey', 'horse', 'house', 'human',
  'jolly', 'joyful', 'juice', 'jumper', 'kayak', 'kitty', 'koala', 'large', 'laser', 'laugh',
  'lemon', 'lesson', 'letter', 'listen', 'llama', 'lucky', 'lunch', 'magic', 'maker', 'mango',
  'marble', 'marker', 'meadow', 'melon', 'merry', 'metal', 'mother', 'mouse', 'mouth', 'muffin',
  'music', 'nanny', 'nephew', 'niece', 'number', 'nurse', 'ocean', 'onion', 'orange', 'orbit',
  'otter', 'paddle', 'paint', 'panda', 'paper', 'parrot', 'pasta', 'patio', 'peach', 'pearl',
  'pedal', 'pencil', 'person', 'petal', 'plane', 'planet', 'plant', 'player', 'polite', 'porch',
  'potato', 'proud', 'puddle', 'puppy', 'purple', 'puzzle', 'quest', 'quiet', 'rabbit', 'racing',
  'racket', 'recess', 'report', 'river', 'robin', 'robot', 'rocket', 'round', 'ruler', 'saddle',
  'salad', 'sandy', 'scale', 'scoop', 'score', 'season', 'seeds', 'seven', 'share', 'shark',
  'sheep', 'shelf', 'shell', 'shells', 'shiny', 'ships', 'shore', 'shower', 'silly', 'sister',
  'skate', 'sleep', 'sleepy', 'small', 'smart', 'smile', 'snail', 'snappy', 'soccer', 'space',
  'spark', 'spell', 'splash', 'spoon', 'spring', 'square', 'stair', 'stand', 'store', 'storm',
  'stove', 'stream', 'study', 'subway', 'sugar', 'summer', 'sweet', 'swims', 'swing', 'table',
  'teeth', 'tennis', 'three', 'throw', 'thumb', 'tickle', 'tides', 'tiger', 'toast', 'tomato',
  'tooth', 'tower', 'track', 'train', 'travel', 'trophy', 'truck', 'tummy', 'tunnel', 'twenty',
  'uncle', 'valley', 'wagon', 'wander', 'water', 'waves', 'whale', 'wheel', 'white', 'wiggle',
  'window', 'winner', 'winter', 'wrist', 'write', 'yogurt', 'zebra',
]

export const HARD: string[] = [
  'adventure', 'adventurous', 'airplane', 'airport', 'alphabet', 'antelope', 'antenna', 'asteroid', 'astronaut', 'backpack',
  'bakeries', 'balance', 'balcony', 'balloon', 'bandage', 'baseball', 'bathroom', 'beautiful', 'bedroom', 'believe',
  'bicycle', 'biscuit', 'blanket', 'blossom', 'blueberry', 'breathe', 'broccoli', 'brother', 'buffalo', 'builder',
  'building', 'butterfly', 'cabbage', 'calendar', 'captain', 'carriage', 'carrots', 'cartwheel', 'catching', 'ceiling',
  'celebrate', 'chalkboard', 'champion', 'cheerful', 'chicken', 'children', 'circuit', 'classroom', 'coastline', 'collect',
  'colorful', 'compass', 'cookies', 'cottage', 'counter', 'crescent', 'cucumber', 'cupboard', 'curious', 'current',
  'dandelion', 'daughter', 'daylight', 'delightful', 'delivery', 'diamond', 'discover', 'doctors', 'dolphin', 'doorway',
  'drawing', 'dribble', 'driveway', 'drizzle', 'eighteen', 'elephant', 'elevator', 'engineer', 'enormous', 'evening',
  'exercise', 'explore', 'explorer', 'eyebrow', 'eyelash', 'fifteen', 'fingers', 'flamingo', 'flippers', 'football',
  'forehead', 'fountain', 'fourteen', 'freckle', 'friendly', 'frisbee', 'geography', 'gigantic', 'giraffe', 'graceful',
  'grandma', 'grandpa', 'grateful', 'hallway', 'hamster', 'hedgehog', 'helpers', 'hexagon', 'highway', 'history',
  'homework', 'hundred', 'husband', 'imagine', 'jellyfish', 'journey', 'jumping', 'kangaroo', 'kicking', 'kitchen',
  'knuckle', 'knuckles', 'ladders', 'ladybug', 'language', 'letters', 'lettuce', 'library', 'lifeboat', 'lifeguard',
  'lighthouse', 'lightning', 'luggage', 'machine', 'mailbox', 'measure', 'moonlight', 'morning', 'mountain', 'mystery',
  'neighbor', 'nineteen', 'noodles', 'notebook', 'octagon', 'octopus', 'ostrich', 'painter', 'pancake', 'patient',
  'peaceful', 'peacock', 'penguin', 'pentagon', 'picture', 'pineapple', 'planted', 'playful', 'playing', 'popcorn',
  'porridge', 'practice', 'pretend', 'pretzel', 'pumpkin', 'railway', 'rainbow', 'raindrop', 'raspberry', 'reading',
  'rectangle', 'relative', 'running', 'sailboat', 'saltwater', 'sandcastle', 'sandwich', 'satellite', 'schoolbag', 'science',
  'scissor', 'scooter', 'scribble', 'seahorse', 'seashell', 'seashore', 'seaweed', 'seedling', 'seventy', 'shoulder',
  'sixteen', 'skating', 'snorkel', 'snowflake', 'snuggle', 'spaceship', 'sparkle', 'sparkly', 'spelling', 'squirrel',
  'stadium', 'starfish', 'starship', 'station', 'steamboat', 'stomach', 'stranger', 'strawberry', 'stretch', 'student',
  'subject', 'sunflower', 'sunlight', 'sunshine', 'swimmer', 'swimming', 'swimsuit', 'teacher', 'teammate', 'teenager',
  'telescope', 'thankful', 'thirteen', 'thoughtful', 'throwing', 'thunder', 'toddler', 'tortoise', 'tractor', 'trailer',
  'treasure', 'triangle', 'tricycle', 'twinkle', 'umbrella', 'uniform', 'vehicle', 'village', 'waterfall', 'watermelon',
  'weather', 'whisper', 'wonderful', 'workers', 'writing',
]

export const ALL_WORDS: string[] = [...EASY, ...MEDIUM, ...HARD]

export type Difficulty = 'easy' | 'medium' | 'hard'

/** Words for a difficulty tier. */
export function wordsByDifficulty(d: Difficulty): string[] {
  return d === 'easy' ? EASY : d === 'medium' ? MEDIUM : HARD
}

/**
 * A blended pool that ramps with progress: starts easy, mixes in medium, then
 * hard. `progress` is 0..1 (e.g. cleared / target).
 */
export function rampedPool(progress: number): string[] {
  if (progress < 0.34) return [...EASY, ...MEDIUM.slice(0, 20)]
  if (progress < 0.67) return [...EASY, ...MEDIUM]
  return [...MEDIUM, ...HARD]
}
